server:
  port: 8080
  ssl:
    key-store: classpath:server.private
    # JKS 需要两个密码，P12只需要key-store-password
    key-store-password: serverstorepw
    key-password: serverkeypw
    key-store-type: JKS
